name: CodeQL Analysis

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, labeled, synchronize]

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
