name: Deploy to Vercel

on:
  pull_request:
    branches:
      - staging

  push:
    branches:
      - main   
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            vercel --prod
          else
            DEPLOY_URL=$(vercel --prebuilt --confirm)
            echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        env:
          DEPLOY_URL: ${{ env.DEPLOY_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="🚀 Deploy preview disponível em: $DEPLOY_URL"
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -X POST \
               -d "{\"body\": \"$COMMENT\"}" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
