name: Deploy to Vercel (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Project Settings
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel pull --yes --token $VERCEL_TOKEN

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel build
          DEPLOY_URL=$(vercel --prod --token $VERCEL_TOKEN)
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Create GitHub Commit Status
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_URL: ${{ env.DEPLOY_URL }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{
              "state": "success",
              "target_url": "'$DEPLOY_URL'",
              "description": "Deploy to production is live",
              "context": "Vercel Deploy"
            }' \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}